src/ASM-Auto.Web/Controllers/MultimediaController.cs
using ASM_Auto.Services.Common;
using ASM_Auto.ViewModels.Multimedia;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASM_Auto.Web.Controllers
{
    public class MultimediaController : BaseController
    {
        private ICarService carService;
        private IMultimediaService multimediaService;
        private IBackUpCameraService cameraService;
        public MultimediaController(
            ICarService carService,
            IMultimediaService multimediaService,
            IBackUpCameraService cameraService)
        {
            this.carService = carService;
            this.multimediaService = multimediaService;
            this.cameraService = cameraService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Multimedia([FromQuery] MultimediaQueryModel queryModel)
        {
            queryModel.CarMakes = await carService.CarMakes();
            queryModel.Products = await multimediaService.GetProducts(queryModel.currentPage, queryModel.CarMakeId, queryModel.CarModelId, queryModel.OrderedProducts);
            queryModel.ProductCount = await multimediaService.ProductCount();

            return View(queryModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> BackupCameras([FromQuery] MultimediaQueryModel queryModel)
        {
            queryModel.CarMakes = await carService.CarMakes();
            queryModel.Products = await cameraService.GetProducts(queryModel.currentPage, queryModel.CarMakeId, queryModel.CarModelId, queryModel.OrderedProducts);
            queryModel.ProductCount = await cameraService.ProductCount();

            return View(queryModel);
        }
    }
}

src/ASM-Auto.Web/Views/Multimedia/BackupCameras.cshtml
@using ASM_Auto.ViewModels.Multimedia
@model MultimediaQueryModel
@{
    ViewData["Title"] = "Камери за задни виждане";
}
<h2 class="title">Светлини</h2>

<section class="form">

    <form method="get">
        <div class="form-group">
            <label></label>
            <select asp-for="CarMakeId" class="form-control carMakes">
                <option value="" disabled selected hidden>Марка</option>
                @foreach (var make in Model.CarMakes)
                {
                    <option value="@make.CarMakeId">@make.CarMakeText</option>
                }

            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="CarModelId" class="form-control carModels">
                <option value="" disabled selected hidden>Модел</option>

            </select>
        </div>


        <div class="form-group">
            <label></label>

            <select asp-for="OrderedProducts" class="form-control">
                <option value="" disabled selected hidden>Подреди по</option>
                <option value="1">Цена (възходящо)</option>
                <option value="2">Цена (низходящо)</option>
                <option value="0">Най-нови</option>
            </select>
        </div>
        <input type="submit" value="Търсене..." class="sbtBtn" />


    </form>
    <hr class="lineUnForm">

</section>
<section class="products">

    @if (!Model.Products.Any())
    {
        <p class="nf">Няма намерени резултати!</p>
    }
    @foreach (var product in Model.Products)
    {
        <partial name="_PartialProduct" model="@product" />
    }

</section>

@{
    var previosPage = Model.currentPage - 1;

    if (previosPage < 1)
    {
        previosPage = 1;
    }

    var maxPage = Math.Ceiling((double)(Model.ProductCount / MultimediaQueryModel.productsPerPage));
}

@if (Model.Products.Any())
{
    <section class="paginationSection">
        <a class="paginationBtn @(Model.currentPage==1? "isDisabled" : String.Empty)"
       asp-controller="Multimedia"
       asp-action="BackupCameras"
       asp-route-currentPage="@previosPage"
       asp-route-CarMakeId="@Model.CarMakeId"
       asp-route-CarModelId="@Model.CarModelId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Назад
        </a>

        <a class="paginationBtn @(Model.currentPage>=maxPage? "isDisabled" : String.Empty)"
       asp-controller="Multimedia"
       asp-action="BackupCameras"
       asp-route-currentPage="@(Model.currentPage + 1)"
       asp-route-CarMakeId="@Model.CarMakeId"
       asp-route-CarModelId="@Model.CarModelId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Напред
        </a>
    </section>
}
<script src="/js/get-car-models.js"></script>

src/ASM-Auto.Web/Views/Multimedia/Multimedia.cshtml
@using ASM_Auto.ViewModels.Multimedia
@model MultimediaQueryModel
@{
    ViewData["Title"] = "Мултимедии";
}
<h2 class="title">Светлини</h2>

<section class="form">

    <form method="get">
        <div class="form-group">
            <label></label>
            <select asp-for="CarMakeId" class="form-control carMakes">
                <option value="" disabled selected hidden>Марка</option>
                @foreach (var make in Model.CarMakes)
                {
                    <option value="@make.CarMakeId">@make.CarMakeText</option>
                }

            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="CarModelId" class="form-control carModels">
                <option value="" disabled selected hidden>Модел</option>

            </select>
        </div>


        <div class="form-group">
            <label></label>

            <select asp-for="OrderedProducts" class="form-control">
                <option value="" disabled selected hidden>Подреди по</option>
                <option value="1">Цена (възходящо)</option>
                <option value="2">Цена (низходящо)</option>
                <option value="0">Най-нови</option>
            </select>
        </div>
        <input type="submit" value="Търсене..." class="sbtBtn" />


    </form>
    <hr class="lineUnForm">

</section>
<section class="products">

    @if (!Model.Products.Any())
    {
        <p class="nf">Няма намерени резултати!</p>
    }
    @foreach (var product in Model.Products)
    {
        <partial name="_PartialProduct" model="@product" />
    }

</section>

@{
    var previosPage = Model.currentPage - 1;

    if (previosPage < 1)
    {
        previosPage = 1;
    }

    var maxPage = Math.Ceiling((double)(Model.ProductCount / MultimediaQueryModel.productsPerPage));
}

@if (Model.Products.Any())
{
    <section class="paginationSection">
        <a class="paginationBtn @(Model.currentPage==1? "isDisabled" : String.Empty)"
       asp-controller="Multimedia"
       asp-action="Multimedia"
       asp-route-currentPage="@previosPage"
       asp-route-CarMakeId="@Model.CarMakeId"
       asp-route-CarModelId="@Model.CarModelId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Назад
        </a>

        <a class="paginationBtn @(Model.currentPage>=maxPage? "isDisabled" : String.Empty)"
       asp-controller="Multimedia"
       asp-action="Multimedia"
       asp-route-currentPage="@(Model.currentPage + 1)"
       asp-route-CarMakeId="@Model.CarMakeId"
       asp-route-CarModelId="@Model.CarModelId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Напред
        </a>
    </section>
}
<script src="/js/get-car-models.js"></script>