src/ASM-Auto.Web/Controllers/AutoAccessoriesController.cs
using ASM_Auto.Services.Common;
using ASM_Auto.ViewModels.AutoAccessories.Foils;
using ASM_Auto.ViewModels.AutoAccessories.LedLights;
using ASM_Auto.ViewModels.AutoAccessories.Mats;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASM_Auto.Web.Controllers
{
    public class AutoAccessoriesController : BaseController
    {
        private ILedlightsService ledlightsService;
        private ICarService carService;
        private IMatsService matsService;
        private IFoilService foilService;
        public AutoAccessoriesController(
            ILedlightsService ledlightsService,
            ICarService carService,
            IMatsService matsService,
            IFoilService foilService)
        {
            this.ledlightsService = ledlightsService;
            this.matsService = matsService;
            this.carService = carService;
            this.foilService = foilService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Ledlights([FromQuery] AllLedlightsQueryModel queryModel)
        {
            var products = await ledlightsService.GetLedlights(
                queryModel.currentPage,
                queryModel.LedlightsType,
                queryModel.LedlightsColor,
                queryModel.LedlightsPower,
                queryModel.LedlightsFormat,
                queryModel.OrderedProducts);

            queryModel.LedlightsCount = await ledlightsService.GetLedlightsCount();
            queryModel.LedlightsFormats = await ledlightsService.GetLedlightsFormats();
            queryModel.LedlightsPowers = await ledlightsService.GetLedlightsPower();
            queryModel.LedlightsColors = await ledlightsService.GetLedlightsColors();
            queryModel.LedlightsTypes = await ledlightsService.GetLedlightsTypes();
            queryModel.Ledlights = products;

            return View(queryModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Mats([FromQuery] AllMatsViewModel queryModel)
        {
            queryModel.MatsCount = await matsService.MatsCount();
            queryModel.CarMakes = await carService.CarMakes();
            queryModel.MatsTypes = await matsService.MatsTypes();
            queryModel.Mats = await matsService.GetMats(queryModel.currentPage, queryModel.CarMakeId, queryModel.CarModelId, queryModel.MatsTypeId, queryModel.OrderedProducts);

            return View(queryModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Foils([FromQuery] AllFoilsQueryModel queryModel)
        {
            queryModel.FoilsPurposes = await foilService.GetFoilsPurposes();
            queryModel.FoilsTypes = await foilService.GetTypes();
            queryModel.FoilsColors = await foilService.GetFoilsColors();
            queryModel.FoilsCount = await foilService.GetFoilsCount();
            queryModel.Foils = await foilService.GetFoils(queryModel.currentPage, queryModel.FoilsTypeId, queryModel.FoilsColorId, queryModel.FoilsPurposeId, queryModel.OrderedProducts);

            return View(queryModel);
        }
    }
}

src/ASM-Auto.Web/Views/AutoAccessories/Foils.cshtml
@using ASM_Auto.ViewModels.AutoAccessories.Foils
@model AllFoilsQueryModel
@{
    ViewData["Title"] = "Стелки";
}
<h2 class="title">Светлини</h2>

<section class="form">

    <form method="get">
        <div class="form-group">
            <label></label>
            <select asp-for="FoilsTypeId" class="form-control">
                <option value="" disabled selected hidden>Тип</option>
                @foreach (var type in Model.FoilsTypes)
                {
                    <option value="@type.FoilTypeId">@type.FoilType</option>
                }

            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="FoilsColorId" class="form-control">
                <option value="" disabled selected hidden>Цвят</option>
                 @foreach (var colors in Model.FoilsColors)
                {
                    <option value="@colors.FoilColorId">@colors.FoilColor</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="FoilsPurposeId" class="form-control">
                <option value="" disabled selected hidden>Предназначение</option>
                @foreach (var purpose in Model.FoilsPurposes)
                {
                    <option value="@purpose.FoilPurposeId">@purpose.FoilPurpose</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="OrderedProducts" class="form-control">
                <option value="" disabled selected hidden>Подреди по</option>
                <option value="1">Цена (възходящо)</option>
                <option value="2">Цена (низходящо)</option>
                <option value="0">Най-нови</option>
            </select>
        </div>
        <input type="submit" value="Търсене..." class="sbtBtn" />


    </form>
    <hr class="lineUnForm">

</section>
<section class="products">

    @if (!Model.Foils.Any())
    {
        <p class="nf">Няма намерени резултати!</p>
    }
    @foreach (var product in Model.Foils)
    {
        <partial name="_PartialProduct" model="@product" />
    }

</section>

@{
    var previosPage = Model.currentPage - 1;

    if (previosPage < 1)
    {
        previosPage = 1;
    }

    var maxPage = Math.Ceiling((double)(Model.FoilsCount / AllFoilsQueryModel.productsPerPage));
}

@if (Model.Foils.Any())
{
    <section class="paginationSection">
        <a class="paginationBtn @(Model.currentPage==1? "isDisabled" : String.Empty)"
       asp-controller="AutoAccessories"
       asp-action="Foils"
       asp-route-currentPage="@previosPage"
       asp-route-FoilsPurposeId="@Model.FoilsPurposeId"
       asp-route-FoilsTypeId="@Model.FoilsTypeId"
       asp-route-FoilsColorId="@Model.FoilsColorId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Назад
        </a>

        <a class="paginationBtn @(Model.currentPage>=maxPage? "isDisabled" : String.Empty)"
       asp-controller="AutoAccessories"
       asp-action="Foils"
       asp-route-currentPage="@(Model.currentPage + 1)"
       asp-route-FoilsPurposeId="@Model.FoilsPurposeId"
       asp-route-FoilsTypeId="@Model.FoilsTypeId"
       asp-route-FoilsColorId="@Model.FoilsColorId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Напред
        </a>
    </section>
}

src/ASM-Auto.Web/Views/AutoAccessories/Ledlights.cshtml
@using ASM_Auto.ViewModels.AutoAccessories.LedLights
@model AllLedlightsQueryModel
@{
    ViewData["Title"] = "Светлини";
}
<h2 class = "title">Светлини</h2>

<section class="form">

<form method="get">
    <div class="form-group">
            <label></label>
            <select asp-for="LedlightsType" class="form-control">
                    <option value="" disabled selected hidden>Тип</option>
                    @foreach (var type in Model.LedlightsTypes)
                    {
                       <option value="@type.LedlightType">@type.LedlightType</option>
                    }
                    
                </select>
            </div>

               <div class="form-group">
                <label ></label>

            <select asp-for="LedlightsColor" class="form-control">
                    <option value="" disabled selected hidden>Цвят</option>
                @foreach (var color in Model.LedlightsColors)
                {
                    <option value="@color.LedlightColor">@color.LedlightColor</option>
                }
                </select>
            </div>

               <div class="form-group">
                <label ></label>

                <select asp-for="LedlightsPower" class="form-control">
                    <option value="" disabled selected hidden> Мощност</option>
                    @foreach (var power in Model.LedlightsPowers)
                {
                    <option value="@power.LedlightPower">@power.LedlightPower</option>
                }
                </select>
            </div>

               <div class="form-group">
                <label ></label>

            <select asp-for="LedlightsFormat" class="form-control">
                    <option value="" disabled selected hidden>Размер</option>
                @foreach (var format in Model.LedlightsFormats)
                {
                    <option value="@format.LedlightFormat">@format.LedlightFormat</option>
                }
                </select>
            </div>
             <div class="form-group">
                <label ></label>

            <select asp-for="OrderedProducts" class="form-control">
                    <option value="" disabled selected hidden>Подреди по</option>
                    <option value="1">Цена (възходящо)</option>
                    <option value="2">Цена (низходящо)</option>
                    <option value="0">Най-нови</option>
                </select>
            </div>
    <input type="submit" value="Търсене..." class ="sbtBtn" />


</form>
<hr class ="lineUnForm">

</section>
<section class="products">

    @if (!Model.Ledlights.Any()) {
        <p class="nf">Няма намерени резултати!</p>
    }
    @foreach (var product in Model.Ledlights)
    {
        <partial name="_PartialProduct" model="@product" />
    }
   
</section>

@{
    var previosPage = Model.currentPage - 1;

    if (previosPage<1)
    {
        previosPage = 1;
    }

    var maxPage =Math.Ceiling((double)(Model.LedlightsCount / AllLedlightsQueryModel.productsPerPage));
}

@if (Model.Ledlights.Any()) { 
    <section class="paginationSection">
   <a
    class="paginationBtn @(Model.currentPage==1? "isDisabled" : String.Empty)"
   asp-controller="AutoAccessories"
   asp-action="Ledlights"
   asp-route-currentPage="@previosPage"
   asp-route-LedlightsType ="@Model.LedlightsType"
   asp-route-LedlightsColor="@Model.LedlightsColor"
   asp-route-LedlightsPower="@Model.LedlightsPower"
   asp-route-LedlightsFormat="@Model.LedlightsFormat"
   asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
   Назад
   </a>

<a class="paginationBtn @(Model.currentPage>=maxPage? "isDisabled" : String.Empty)"
   asp-controller="AutoAccessories"
   asp-action="Ledlights"
   asp-route-currentPage="@(Model.currentPage + 1)"
   asp-route-LedlightsType="@Model.LedlightsType"
   asp-route-LedlightsColor="@Model.LedlightsColor"
   asp-route-LedlightsPower="@Model.LedlightsPower"
   asp-route-LedlightsFormat="@Model.LedlightsFormat"
   asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
    Напред
</a>
</section>
}

src/ASM-Auto.Web/Views/AutoAccessories/Mats.cshtml
@using ASM_Auto.ViewModels.AutoAccessories.Mats
@model AllMatsViewModel
@{
    ViewData["Title"] = "Стелки";
}
<h2 class="title">Светлини</h2>

<section class="form">

    <form method="get">
        <div class="form-group">
            <label></label>
            <select asp-for="CarMakeId" class="form-control carMakes">
                <option value="" disabled selected hidden>Марка</option>
                @foreach (var make in Model.CarMakes)
                {
                    <option value="@make.CarMakeId">@make.CarMakeText</option>
                }

            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="CarModelId" class="form-control carModels">
                <option value="" disabled selected hidden>Модел</option>
 
            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="MatsTypeId" class="form-control">
                <option value="" disabled selected hidden>Тип</option>
                @foreach (var types in Model.MatsTypes)
                {
                    <option value="@types.MatsTypeId">@types.MatsTypeName</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="OrderedProducts" class="form-control">
                <option value="" disabled selected hidden>Подреди по</option>
                <option value="1">Цена (възходящо)</option>
                <option value="2">Цена (низходящо)</option>
                <option value="0">Най-нови</option>
            </select>
        </div>
        <input type="submit" value="Търсене..." class="sbtBtn" />


    </form>
    <hr class="lineUnForm">

</section>
<section class="products">

    @if (!Model.Mats.Any())
    {
        <p class="nf">Няма намерени резултати!</p>
    }
    @foreach (var product in Model.Mats)
    {
        <partial name="_PartialProduct" model="@product" />
    }

</section>

@{
    var previosPage = Model.currentPage - 1;

    if (previosPage < 1)
    {
        previosPage = 1;
    }

    var maxPage = Math.Ceiling((double)(Model.MatsCount / AllMatsViewModel.productsPerPage));
}

@if (Model.Mats.Any())
{
    <section class="paginationSection">
        <a class="paginationBtn @(Model.currentPage==1? "isDisabled" : String.Empty)"
       asp-controller="AutoAccessories"
       asp-action="Mats"
       asp-route-currentPage="@previosPage"
       asp-route-CarMakeId="@Model.CarMakeId"
       asp-route-CarModelId="@Model.CarModelId"
       asp-route-MatsTypeId="@Model.MatsTypeId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Назад
        </a>

        <a class="paginationBtn @(Model.currentPage>=maxPage? "isDisabled" : String.Empty)"
       asp-controller="AutoAccessories"
       asp-action="Mats"
       asp-route-currentPage="@(Model.currentPage + 1)"
       asp-route-CarMakeId="@Model.CarMakeId"
       asp-route-CarModelId="@Model.CarModelId"
       asp-route-MatsTypeId="@Model.MatsTypeId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Напред
        </a>
    </section>
}
<script src="/js/get-car-models.js"></script>