src/ASM-Auto.Web/Controllers/AutoCosmeticsController.cs
using ASM_Auto.Services.Common;
using ASM_Auto.ViewModels.AutoCosmetics.Autoshampoo;
using ASM_Auto.ViewModels.AutoCosmetics.CleaningAccessories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASM_Auto.Web.Controllers
{
    public class AutoCosmeticsController : BaseController
    {   
        private IAutoshampooService autoshampooService;
        private ICleaningAccessoryService accessoryService;
        public AutoCosmeticsController(
            IAutoshampooService autoshampooService,
            ICleaningAccessoryService accessoryService)
        {
            this.autoshampooService = autoshampooService;
            this.accessoryService = accessoryService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Autoshampoo([FromQuery] AllAutoshampooQuery queryModel)
        {
            queryModel.Shampoos = await autoshampooService.GetShampoos(queryModel.currentPage, queryModel.OrderedProducts);
            queryModel.ShampoosCount = await autoshampooService.GetShampooCount();

            return View(queryModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> CleaningAccessories([FromQuery] CleaningAccessoriesQueryModel queryModel)
        {
            queryModel.AccessoriesType = await accessoryService.GetCleaningTypes();
            queryModel.AccessoriesCount = await accessoryService.GetAccessoriesCount();
            queryModel.Accessories = await accessoryService.GetCleaningAccesories(queryModel.currentPage, queryModel.AccessoriesTypeId, queryModel.OrderedProducts);

            return View(queryModel);
        }
    }
}

src/ASM-Auto.Web/Views/AutoCosmetics/Autoshampoo.cshtml
@using ASM_Auto.ViewModels.AutoCosmetics.Autoshampoo
@model AllAutoshampooQuery
@{
    ViewData["Title"] = "Стелки";
}
<h2 class="title">Автошампоани</h2>

<section class="form">

    <form method="get">

        <div class="form-group">
            <label></label>

            <select asp-for="OrderedProducts" class="form-control">
                <option value="" disabled selected hidden>Подреди по</option>
                <option value="1">Цена (възходящо)</option>
                <option value="2">Цена (низходящо)</option>
                <option value="0">Най-нови</option>
            </select>
        </div>
        <input type="submit" value="Търсене..." class="sbtBtn" />


    </form>
    <hr class="lineUnForm">

</section>
<section class="products">

    @if (!Model.Shampoos.Any())
    {
        <p class="nf">Няма намерени резултати!</p>
    }
    @foreach (var product in Model.Shampoos)
    {
        <partial name="_PartialProduct" model="@product" />
    }

</section>

@{
    var previosPage = Model.currentPage - 1;

    if (previosPage < 1)
    {
        previosPage = 1;
    }

    var maxPage = Math.Ceiling((double)(Model.ShampoosCount / AllAutoshampooQuery.productsPerPage));
}

@if (Model.Shampoos.Any())
{
    <section class="paginationSection">
        <a class="paginationBtn @(Model.currentPage==1? "isDisabled" : String.Empty)"
       asp-controller="AutoCosmetics"
       asp-action="Autoshampoo"
       asp-route-currentPage="@previosPage"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Назад
        </a>

        <a class="paginationBtn @(Model.currentPage>=maxPage? "isDisabled" : String.Empty)"
       asp-controller="AutoCosmetics"
       asp-action="Autoshampoo"
       asp-route-currentPage="@(Model.currentPage + 1)"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Напред
        </a>
    </section>
}

src/ASM-Auto.Web/Views/AutoCosmetics/CleaningAccessories.cshtml
@using ASM_Auto.ViewModels.AutoCosmetics.CleaningAccessories
@model CleaningAccessoriesQueryModel
@{
    ViewData["Title"] = "Стелки";
}
<h2 class="title">Автошампоани</h2>

<section class="form">

    <form method="get">

        <div class="form-group">
            <label></label>
            <select asp-for="AccessoriesTypeId" class="form-control carMakes">
                <option value="" disabled selected hidden>Тип</option>
                @foreach (var type in Model.AccessoriesType)
                {
                    <option value="@type.CleaningAccessoryId">@type.CleaningAccessoryName</option>
                }

            </select>
        </div>

        <div class="form-group">
            <label></label>

            <select asp-for="OrderedProducts" class="form-control">
                <option value="" disabled selected hidden>Подреди по</option>
                <option value="1">Цена (възходящо)</option>
                <option value="2">Цена (низходящо)</option>
                <option value="0">Най-нови</option>
            </select>
        </div>
        <input type="submit" value="Търсене..." class="sbtBtn" />


    </form>
    <hr class="lineUnForm">

</section>
<section class="products">

    @if (!Model.Accessories.Any())
    {
        <p class="nf">Няма намерени резултати!</p>
    }
    @foreach (var product in Model.Accessories)
    {
        <partial name="_PartialProduct" model="@product" />
    }

</section>

@{
    var previosPage = Model.currentPage - 1;

    if (previosPage < 1)
    {
        previosPage = 1;
    }

    var maxPage = Math.Ceiling((double)(Model.AccessoriesCount / CleaningAccessoriesQueryModel.productsPerPage));
}

@if (Model.Accessories.Any())
{
    <section class="paginationSection">
        <a class="paginationBtn @(Model.currentPage==1? "isDisabled" : String.Empty)"
       asp-controller="Autocosmetics"
       asp-action="CleaningAccessories"
       asp-route-currentPage="@previosPage"
       asp-route-AccessoriesTypeId="@Model.AccessoriesTypeId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Назад
        </a>

        <a class="paginationBtn @(Model.currentPage>=maxPage? "isDisabled" : String.Empty)"
       asp-controller="AutoCosmetics"
       asp-action="CleaningAccessories"
       asp-route-currentPage="@(Model.currentPage + 1)"
       asp-route-AccessoriesTypeId="@Model.AccessoriesTypeId"
       asp-route-OrderedProducts="@((int)Model.OrderedProducts)">
            Напред
        </a>
    </section>
}