src/ASM-Auto.Web/Areas/Administration/Controllers/CreateProductController.cs
using ASM_Auto.Services.Common;
using ASM_Auto.ViewModels.Administration.CreateProducts;
using Microsoft.AspNetCore.Mvc;

namespace ASM_Auto.Web.Areas.Administration.Controllers
{
    public class CreateProductController : BaseController
    {
        private ILedlightsService ledlightsService;
        private ICarService carService;
        private IMatsService matsService;
        private IFoilService foilService;
        private IAutoshampooService autoshampooService;
        private ICleaningAccessoryService accessoryService;
        private IMultimediaService multimediaService;
        private IBackUpCameraService backUpCameraService;
        public CreateProductController(
            ILedlightsService ledlightsService,
            ICarService carService,
            IMatsService matsService,
            IFoilService foilService,
            IAutoshampooService autoshampooService,
            ICleaningAccessoryService accessoryService,
            IMultimediaService multimediaService,
            IBackUpCameraService backUpCameraService)
        {
            this.ledlightsService = ledlightsService;
            this.carService = carService;
            this.matsService = matsService;
            this.foilService = foilService;
            this.autoshampooService = autoshampooService;
            this.accessoryService = accessoryService;
            this.multimediaService = multimediaService;
            this.backUpCameraService = backUpCameraService;
        }

        [HttpGet]
        public async Task<IActionResult> CreateLedLights()
        {
            var model = new CreateLedLightViewModel();
            model.LedlightsColors = await ledlightsService.GetLedlightsColors();
            model.LedlightsFormats = await ledlightsService.GetLedlightsFormats();
            model.LedlightsPowers = await ledlightsService.GetLedlightsPower();
            model.LedlightsTypes = await ledlightsService.GetLedlightsTypes();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateLedLights(CreateLedLightViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.LedlightsColors = await ledlightsService.GetLedlightsColors();
                model.LedlightsFormats = await ledlightsService.GetLedlightsFormats();
                model.LedlightsPowers = await ledlightsService.GetLedlightsPower();
                model.LedlightsTypes = await ledlightsService.GetLedlightsTypes();

                return View(model);
            }

            try
            {
                await ledlightsService.CreateLedLight(model);
                return RedirectToAction("Index", "Admin");
            }

            catch (Exception)
            {
                return View("Error");
            }

        }

        [HttpGet]
        public async Task<IActionResult> CreateMats()
        {
            var model = new CreateMatViewModel();
            model.MatsTypes = await matsService.MatsTypes();
            model.CarMakes = await carService.CarMakes();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateMats(CreateMatViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.MatsTypes = await matsService.MatsTypes();
                model.CarMakes = await carService.CarMakes();

                return View(model);
            }

            try
            {
                await matsService.CreateMat(model);
                return RedirectToAction("Index", "Admin");
            }

            catch (Exception)
            {
                return View("Error");
            }

        }

        [HttpGet]
        public async Task<IActionResult> CreateFoils()
        {
            var model = new CreateFoilViewModel();
            model.FoilsPurposes = await foilService.GetFoilsPurposes();
            model.FoilsColors = await foilService.GetFoilsColors();
            model.FoilsTypes = await foilService.GetTypes();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateFoils(CreateFoilViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.FoilsPurposes = await foilService.GetFoilsPurposes();
                model.FoilsColors = await foilService.GetFoilsColors();
                model.FoilsTypes = await foilService.GetTypes();
                return View(model);
            }

            try
            {
                await foilService.CreateFoil(model);
                return RedirectToAction("Index", "Admin");
            }
            catch (Exception)
            {

                return View("Error");
            }

        }

        [HttpGet]
        public async Task<IActionResult> CreateAutoshampoo()
        {
            var model = new CreateAutoshampooViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAutoshampoo(CreateAutoshampooViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await autoshampooService.CreateAutoshampoo(model);
                return RedirectToAction("Index", "Admin");
            }

            catch (Exception)
            {

                return View("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> CreateCleaningAccessories()
        {
            var model = new CreateCleaningAccessories();
            model.cleaningAccessories = await accessoryService.GetCleaningTypes();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCleaningAccessories(CreateCleaningAccessories model)
        {
            if (!ModelState.IsValid)
            {
                model.cleaningAccessories = await accessoryService.GetCleaningTypes();
                return View(model);
            }

            try
            {
                await accessoryService.CreateAccessory(model);
                return RedirectToAction("Index", "Admin");
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> CreateMultimedia()
        {
            var model = new CreateNavigationViewModel();
            model.CarMakes = await carService.CarMakes();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateMultimedia(CreateNavigationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.CarMakes = await carService.CarMakes();
                return View(model);
            }

            try
            {
                await multimediaService.CreateMultimedia(model);
                return RedirectToAction("Index", "Admin");
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> CreateBackupCameras()
        {
            var model = new CreateBackupCamerasViewModel();
            model.CarMakes = await carService.CarMakes();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBackupCameras(CreateBackupCamerasViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.CarMakes = await carService.CarMakes();
                return View(model);
            }

            try
            {
                await backUpCameraService.CreateBackUpCamera(model);
                return RedirectToAction("Index", "Admin");
            }

            catch (Exception)
            {
                return View("Error");
            }
        }
    }
}

src/ASM-Auto.Web/Areas/Administration/Controllers/ManageOrdersController.cs
using ASM_Auto.Data.Models.Enums.Order;
using ASM_Auto.Services.Common;
using ASM_Auto.ViewModels.Administration.ManageOrders;
using Microsoft.AspNetCore.Mvc;

namespace ASM_Auto.Web.Areas.Administration.Controllers
{
    public class ManageOrdersController : BaseController
    {
        private IOrderService orderService;
        public ManageOrdersController(IOrderService orderService)
        {
            this.orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> AllOrders(OrderStatus Status = OrderStatus.Pending)
        {
            var model = new AllManageOrdersViewModel();
            model.Orders = await orderService.ManageOrders(Status);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Manage([FromQuery] int Order)
        {
            var model = await orderService.Manage(Order);

            return View(model);
        }

        [HttpGet]
        public async Task<TaskStatus> ChangeStatus([FromQuery] int orderId, int statusId)
        {
            var model = orderService.ChangeStatus(orderId, statusId);

            return model.Status;
        }
    }
}

src/ASM-Auto.Web/Areas/Administration/Controllers/ProductController.cs
using ASM_Auto.Services.Common;
using ASM_Auto.ViewModels;
using ASM_Auto.ViewModels.Administration.Products;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ASM_Auto.Web.Areas.Administration.Controllers
{
    public class ProductController : BaseController
    {
        private IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        public async Task<IActionResult> All([FromQuery] AllProductsQueryModel model)
        {
            var products = await productService.GetProducts(model.currentPage, model.ProductTypeId, model.IsActive, model.OrderedProducts);
            model.ProductTypes = await productService.GetProductTypes();
            model.Products = products;
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid productId)
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;

            try
            {
                var product = await productService.GetProductById(productId);
                var model = new DetailsViewModel()
                {
                    productId = product.ProductId,
                    Title = product.Title,
                    Images = product.Images,
                    Description = product.Description,
                    LineDescription = product.LineDescription,
                    Price = product.Price,
                    Type = product.ProductType.Type,
                    Category = product.ProductType.Category.CategoryName,
                    Make = product.CarMake?.CarMakeText ?? null,
                    Model = product.CarModel?.CarModelText ?? null,
                    NewPrice = product.NewPrice ?? null,
                    IsAvailable = product.IsAvailable,
                    IsFreeDelivery = product.FreeDelivery

                };

                return View(model);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
    }
}

src/ASM-Auto.Web/Areas/Administration/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>@ViewData["Title"] - ASM Auto</title>
    <link rel="stylesheet" href="~/css/_Admin-layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main-page.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/product-details.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cart.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/orders.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/liked-products.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/admin-area.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav>
            <section class="user-nav">
            <ul class="nav">
            </ul>
            </section>
            <section class="logo">
                <h1>ASM<span>Auto</span></h1>
                <h2>Всичко за вашия автомобил!</h2>

                <h2 class="admTitle">АДМИНИСТРАЦИЯ</h2>
            </section>

            <section class="category-nav">
                <ul class="nav">
                    <li class="back">
                        <a asp-area="" asp-controller="Home" asp-action="Index">НАЗАД</a>
                    </li>

                    <div class="dropdown">
                        <button class="dropbtn">
                            ДОБАВИ ПРОДУКТ
             
                        </button>
                        <div class="dropdown-content">
                            <a asp-area="Administration" asp-controller="CreateProduct" asp-action="CreateLedlights">ЛЕД ОСВЕТЛЕНИЕ</a>
                            <a asp-area="Administration" asp-controller="CreateProduct" asp-action="CreateMats">СТЕЛКИ</a>
                            <a asp-area="Administration" asp-controller="CreateProduct" asp-action="CreateFoils">ФОЛИО</a>
                            <a asp-area="Administration" asp-controller="CreateProduct" asp-action="CreateAutoshampoo">АВТОШАМПОАНИ</a>
                            <a asp-area="Administration" asp-controller="CreateProduct" asp-action="CreateCleaningAccessories">ПОЧИСТВАЩИ ПРИНАДЛЕЖНОСТИ</a>
                            <a asp-area="Administration" asp-controller="CreateProduct" asp-action="CreateMultimedia">МУЛТИМЕДИИ</a>
                            <a asp-area="Administration" asp-controller="CreateProduct" asp-action="CreateBackupCameras">КАМЕРИ ЗА ЗАДНО ВИЖДАНЕ</a>
                        </div>
                    </div>

                    <li >
                        <a asp-area="Administration" asp-controller="Product" asp-action="All">УПРАВЛЕНИЕ НА ПРОДУКТИТЕ</a>
                    </li>

                    <li>
                        <a asp-area="Administration" asp-controller="ManageOrders" asp-action="AllOrders">ПОРЪЧКИ</a>
                    </li>

                 
                </ul>
                
            </section>
        </nav>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
    <div class="footer">
        <section class="Links">
            <h3>ASM<span>Auto</span></h3>
            <p>ASMAuto е онлайн магазин за <br> качествени автомобилни продукти!</p>
        </section>
      
        </div>

        <div class="secfooter">
            <p>&copy; @DateTime.UtcNow.Year - ASMAuto. Всички правя запазени!</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

src/ASM-Auto.Web/Areas/Administration/Views/Shared/_PartialProduct.cshtml
@using ASM_Auto.ViewModels
@model PartialProductModel
<div class="card">
                  <a href="/Product/Details?productId=@Model.ProductId">
  <img src="@Model.ImageUrl" alt="@Model.Title" style="width:100%">
  <h1>@Model.Title</h1>
  <p class="price">@Model.Price лв.</p>
  <p>@Model.Description</p>

    <p><button>Виж продукта</button></p>
    </a>
</div>